TextInput 컴포넌트 테스트 코드 추가
Autopedia/react-native-ui pull request #65
Opened 2021-07-26 08:02 UTC by moowoonsunghoon

[테크스펙](https://docs.google.com/document/d/1HXw2nb3DtbADkH50TXjWs6JkT5rgKoBwhJ2ZXUTB05w/edit#heading=h.esb7a2uoipbx)

Coverage
100%

1. TextInput컴포넌트 multiline 상태이며 numberOfLines prop이 지정되지않은 ui snapshot 추가
2. disabled상태일때 secureTextEntry icon 미작동 여부 테스트 코드 추가

5시30분까지 리뷰 부탁드릴게요!

2021-07-26 12:42 UTC, moowoonsunghoon commented
Icon 컴포넌트 자체가 disabled가 true 일시에는 onPress가 undefined로 처리되어 disabled시 event작동 여부 테스트 코드가 불필요하여 제거했고 이와같은 이유로 setShowText안에 콜백함수로 작동하는 코드도 수정하였습니다.

2021-07-27 04:03 UTC, SeungsuKim requested changes

2021-07-27 04:03 UTC, SeungsuKim commented on src/atoms/TextInput/TextInput.tsx
> +                setShowText(!showText);
**P2**: `showText` 값을 toggle할 때는 

```typescript
setShowText(showText => !showText)
```

와 같이 toggle하시는 것이 좋습니다. 이전 state에 기반해 새로운 state를 설정할 때는 항상 value가 아닌 함수를 이용해주시길 바랍니다.

2021-07-27 04:09 UTC, moowoonsunghoon commented on src/atoms/TextInput/TextInput.tsx
> +                setShowText(!showText);
@SeungsuKim 
네! 수정완료했습니다!

2021-07-27 04:09 UTC, SeungsuKim approved these changes

2021-07-27 04:12 UTC, merged